### ISSUE TITLE
more parameters in transform for 2-year institutions

### ISSUE THREAD

**Issue by gdenicolo** [jbryer/ipeds#18]
I am a "copy-paste/google_everything"-type of python user, a teacher at 2-year college, and also work on professional development for 2-year faculty. I'd like to use python and colab to select IPEDS samples for 2YCs, specially involving student enrollment split by ethnicity, and financial aid. 
I wish your library could make this easier for us, as we are definitely a struggling community (both in lack of data visibility and handling codes on our own!). 
Thanks for reading!
Glenda (glenda.denicolo AT gmail.com)

**Comment by jbryer** [comment]
I appreciate your position Glenda. I was in a similar situation when I created the ipeds package. Unfortunately I am not a python programmer and have too many commitments right now to even explore that option. The package is licensed under GPL so anyone is welcome to use it as a way of moving to Python.
