### ISSUE TITLE
Vignette not available 

### ISSUE THREAD

**Issue by dcaud** [jbryer/ipeds#4]
After `devtools::install_github('jbryer/ipeds')`

I get:

`> vignette('ipeds')
Warning message:
vignette ‘ipeds’ not found `

**Comment by jbryer** [comment]
Did you load the package first?

**Comment by dcaud** [comment]
Yes.

This:
`library(ipeds)
vignette('ipeds') `

gives the message above.

This:
`available_ipeds()`

seems to work (give a dataframe with 13 rows 

However, this:
`ipeds_survey(table = 'HD', year = 2018)`

results in:
`Error in load_ipeds(year = year, dir = dir) : 
  Data file for 2017-18 not available. Try running the following function first:
download_ipeds(year = 2018, dir = "/Users/ryanpfleger/Library/R/3.5/library/ipeds/data/downloaded/")`

And running that other function didn't work either.

**Comment by dcaud** [comment]
BTW, I'm on a mac and installed mdbtools. Here's some details of my setup:

```platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          5.2                         
year           2018                        
month          12                          
day            20                          
svn rev        75870                       
language       R                           
version.string R version 3.5.2 (2018-12-20)
nickname       Eggshell Igloo
```

**Comment by jzadra** [comment]
I also get the same error with the vignette.  I'm on 2.0.1

**Comment by tyleransom** [comment]
Ditto for me

**Comment by jbryer** [comment]
Seems the install_github does not build Vignettes by default. Try this command:

```
devtools::install_github('jbryer/ipeds', build_vignettes = TRUE)
```

**Comment by tyleransom** [comment]
Worked for me!
